/* eslint-disable no-use-before-define */
export const router = {
  main: '/',
  shop: 'shop',
  basket: 'basket',
  like: 'like',
  user: 'user',
  info: 'info',
  about: 'about',
  ourshop: 'ourshop',
  reviews: 'reviews',
  question: 'question',
  entrance: 'entrance',
  auth: 'auth',
  reg: 'reg',
  error: '*',
  search: 'search',
  product: 'shop/:id',
  panel: 'panel',
  addProduct: 'panel/addProduct',
};
